server:
  port: 5503
  host: localhost
auth:
  jwksUri: http://localhost:5501/.well-known/jwks.json
database:
  url: mongodb+srv://zahidhasanzh004:uhz1IhzSSf45wawG@cluster0.bpjfvnf.mongodb.net
  
frontend:
  adminUI: http://localhost:5173
  clientUI: http://localhost:3000